# Generated by Django 4.1.4 on 2022-12-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_user_library_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='library',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.library'),
        ),
        migrations.AlterField(
            model_name='user',
            name='library_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
