# Generated by Django 4.1.4 on 2022-12-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_user_library_alter_user_library_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='library',
        ),
    ]
