# Generated by Django 4.1.4 on 2022-12-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_remove_user_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reader_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.readingroom'),
        ),
    ]
