# Generated by Django 4.1.4 on 2022-12-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_alter_book_cypher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='own_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
