# Generated by Django 4.1.4 on 2022-12-25 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_alter_bookcopy_own_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
