# Generated by Django 4.1.4 on 2022-12-28 08:49

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_alter_bookcopy_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='library_card_number',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
