# Generated by Django 4.1.4 on 2022-12-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0012_alter_user_library_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='library_card_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
