# Generated by Django 4.1.1 on 2022-10-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tablo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration_user",
            name="password",
            field=models.CharField(max_length=3, verbose_name="Пароль"),
        ),
    ]
