# Generated by Django 4.1.1 on 2022-10-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tablo", "0002_alter_registration_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration_user",
            name="password",
            field=models.CharField(max_length=300, verbose_name="Пароль"),
        ),
    ]
