# Generated by Django 4.1.1 on 2022-11-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_doc',
            name='id_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='blog.transport_owner'),
        ),
    ]
