from django.shortcuts import render
from django.http import Http404
from django.http import HttpResponse
from .get_car_owner_info import get_car_owner_info
from .get_cars_owners_list import get_cars_owners_list
from .create_car_owner import create_car_owner
from .get_car_info import GetCarInfo
from .get_cars_list import GetCarsList
from .update_car_info import UpdateCarInfo
from .delete_car_info import DeleteCarInfo
from .create_car_info import CreateCarInfo
