# Generated by Django 4.1.2 on 2022-10-15 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('History', 'History'), ('Art', 'Art'), ('English', 'English')], max_length=30)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('task_description', models.TextField()),
                ('fine_info', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1)),
                ('number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('History', 'History'), ('Art', 'Art'), ('English', 'English')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='with_additional_info',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.student')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.studentgroup'),
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.studentgroup'),
        ),
    ]
