# Generated by Django 4.1.2 on 2022-10-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_homework_studentgroup_teacher_student_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.student')),
            ],
        ),
    ]
