# Generated by Django 4.1.2 on 2022-10-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_student_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='max_points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homeworkanswer',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='homework',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
