# Generated by Django 4.1.2 on 2022-10-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_homework_max_points_homeworkanswer_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkanswer',
            name='answer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
