# Generated by Django 4.1.2 on 2022-10-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_homeworkanswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkanswer',
            name='teacher_message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
