# Generated by Django 4.1.2 on 2022-10-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_homeworkanswer_teacher_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkanswer',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
