# Generated by Django 4.1.2 on 2022-10-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_alter_homeworkanswer_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkanswer',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='teacher_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
