# Generated by Django 4.1.2 on 2022-10-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_alter_homeworkanswer_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAnswerOnHomework',
            fields=[
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='timetable.homeworkanswer')),
                ('points', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.teacher')),
            ],
        ),
    ]
