# Generated by Django 4.1.2 on 2022-10-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_teacheransweronhomework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacheransweronhomework',
            old_name='homework',
            new_name='homework_answer',
        ),
    ]
