# Generated by Django 4.1.2 on 2022-10-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_rename_homework_teacheransweronhomework_homework_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkanswer',
            name='points',
        ),
        migrations.RemoveField(
            model_name='homeworkanswer',
            name='teacher_message',
        ),
    ]
