# Generated by Django 4.1.2 on 2022-10-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_remove_homeworkanswer_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='end_date',
            field=models.DateField(verbose_name='Сдать до'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='fine_info',
            field=models.CharField(max_length=150, verbose_name='Информация о штрафах'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='max_points',
            field=models.IntegerField(verbose_name='Максимальное количество баллов'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='start_date',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.CharField(choices=[('Математика', 'Математика'), ('История', 'История'), ('ИЗО', 'ИЗО'), ('Русский язык', 'Русский язык'), ('География', 'География')], max_length=30, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='task_description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='character',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1, verbose_name='Литера'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('Математика', 'Математика'), ('История', 'История'), ('ИЗО', 'ИЗО'), ('Русский язык', 'Русский язык'), ('География', 'География')], max_length=30, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='teacheransweronhomework',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='teacheransweronhomework',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
