# Generated by Django 4.1.2 on 2022-10-19 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0013_alter_homework_end_date_alter_homework_fine_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birthdate',
        ),
    ]
