# Generated by Django 4.1.2 on 2022-10-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0014_remove_student_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='end_date',
            field=models.DateTimeField(verbose_name='Сдать до'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='homeworkanswer',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
