# Generated by Django 4.1.5 on 2023-03-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival_place',
            field=models.CharField(choices=[('Moscow', 'Moscow'), ('Saint-Petersburg', 'Saint-Petersburg'), ('Kaliningrad', 'Kaliningrad'), ('Sochi', 'Sochi'), ('Nalchik', 'Nalchik'), ('Grozny', 'Grozny'), ('Mahachkala', 'Mahachkala'), ('Krasnodar', 'Krasnodar'), ('Anapa', 'Anapa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='out_place',
            field=models.CharField(choices=[('Moscow', 'Moscow'), ('Saint-Petersburg', 'Saint-Petersburg'), ('Kaliningrad', 'Kaliningrad'), ('Sochi', 'Sochi'), ('Nalchik', 'Nalchik'), ('Grozny', 'Grozny'), ('Mahachkala', 'Mahachkala'), ('Krasnodar', 'Krasnodar'), ('Anapa', 'Anapa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='type_of_flight',
            field=models.CharField(choices=[('Arrival', 'Arrival'), ('Departure', 'Departure')], max_length=9),
        ),
    ]
