# Generated by Django 4.1.7 on 2023-02-24 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id_flight",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("source", models.CharField(max_length=50)),
                ("destination", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("airline", models.CharField(max_length=50)),
                (
                    "comfort",
                    models.CharField(
                        choices=[("E", "Economy"), ("B", "Business"), ("F", "First")],
                        max_length=2,
                    ),
                ),
                ("seat_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id_review", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                (
                    "date_reviewed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="flights.flight"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id_booking", models.AutoField(primary_key=True, serialize=False)),
                (
                    "luggage",
                    models.CharField(choices=[("Y", "YES"), ("N", "NO")], max_length=2),
                ),
                (
                    "approved",
                    models.CharField(
                        choices=[("Y", "YES"), ("N", "NO")], default="N", max_length=2
                    ),
                ),
                ("ticket_number", models.CharField(blank=True, max_length=30)),
                (
                    "id_flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="flights.flight"
                    ),
                ),
                (
                    "passport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
