# Generated by Django 4.1.2 on 2022-11-01 13:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Employee')),
                ('first_name_employee', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name_employee', models.CharField(max_length=30, verbose_name='Last name')),
                ('phone_employee', models.CharField(max_length=12, verbose_name='Phone')),
            ],
            options={
                'ordering': ['first_name_employee', 'last_name_employee'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id_guest', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Guest')),
                ('first_name_guest', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name_guest', models.CharField(max_length=30, verbose_name='Last name')),
                ('phone_guest', models.CharField(max_length=12, verbose_name='Phone')),
                ('passport_guest', models.CharField(max_length=10, verbose_name='Passport')),
            ],
            options={
                'ordering': ['first_name_guest', 'last_name_guest'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Hotel')),
                ('name_hotel', models.CharField(max_length=100, verbose_name='Name')),
                ('city_hotel', models.CharField(max_length=30, verbose_name='City')),
                ('address_hotel', models.CharField(max_length=255, verbose_name='Address')),
                ('rating_hotel', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rating')),
                ('des_hotel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id_rt', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Room type')),
                ('type_rt', models.CharField(choices=[('E', 'Econom'), ('S', 'Standard'), ('L', 'Lux')], max_length=1, verbose_name='Type')),
                ('rating_rt', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rating')),
                ('price_rt', models.PositiveIntegerField(verbose_name='Price')),
                ('des_rt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelFirstApp.hotel', verbose_name='ID Hotel')),
            ],
            options={
                'ordering': ['id_rt'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id_room', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Room')),
                ('number_room', models.IntegerField(verbose_name='Number')),
                ('status_room', models.CharField(choices=[('F', 'Free'), ('T', 'Taken'), ('B', 'Booked')], default='F', max_length=1, verbose_name='Status')),
                ('review_room', models.CharField(blank=True, max_length=255, null=True, verbose_name='Review')),
                ('id_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelFirstApp.hotel', verbose_name='ID Hotel')),
                ('id_rt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HotelFirstApp.roomtype', verbose_name='ID Room type')),
            ],
            options={
                'ordering': ['number_room'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id_reg', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Reg')),
                ('status_reg', models.CharField(choices=[('T', 'Taken'), ('B', 'Booked')], max_length=1, verbose_name='Registration status')),
                ('status_pay', models.CharField(choices=[('YP', 'Paid for'), ('NP', 'Not paid for')], max_length=2, verbose_name='Payment status')),
                ('check_in', models.DateField(verbose_name='Check in')),
                ('check_out', models.DateField(verbose_name='Check out')),
                ('booking', models.DateField(verbose_name='Booking date')),
                ('id_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HotelFirstApp.employee', verbose_name='ID Employee')),
                ('id_guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HotelFirstApp.guest', verbose_name='ID Guest')),
                ('id_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HotelFirstApp.room', verbose_name='ID Room')),
            ],
            options={
                'ordering': ['-check_in', '-check_out'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='id_hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelFirstApp.hotel', verbose_name='ID Hotel'),
        ),
    ]
