# Generated by Django 4.1.4 on 2022-12-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_user_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cypher',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
