# Generated by Django 4.1.2 on 2022-10-27 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0002_remove_conference_date_conference_end_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 22, 44, 22, 173287)),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 22, 44, 22, 173287)),
        ),
    ]
