# Generated by Django 4.2 on 2023-04-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='place',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
