# Generated by Django 4.2 on 2023-04-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_remove_ticket_place_delete_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='clas',
            field=models.CharField(blank=True, choices=[('eco', 'econom'), ('bus', 'business')], max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='food',
            field=models.CharField(blank=True, choices=[('in', 'included'), ('not', 'not included')], max_length=15),
        ),
    ]
