# Generated by Django 4.2 on 2023-04-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_ticket_clas_ticket_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='number',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
