# Generated by Django 4.1.2 on 2022-10-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practical_work_1", "0002_alter_car_color_alter_owner_birthday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="cars",
            field=models.ManyToManyField(
                through="practical_work_1.Ownership", to="practical_work_1.car"
            ),
        ),
    ]
