# Generated by Django 4.1.7 on 2023-03-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamebazzar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='added_by',
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
