site_name: My Docs
site_name: Alekseev Paul, K33421

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
 - Знакомство: index.md
 - Лабораторная работа №1: lr1.md
 - Лабораторная работа №2: lr2.md
 - Лабораторная работа №3: lr3.md
 - Практическая работа №3.1: pr3.md
 - Лабораторная работа №4: lr4.md

