# Generated by Django 4.1.2 on 2022-10-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0002_alter_auto_color_alter_owner_date_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="date_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
