# Generated by Django 4.1.7 on 2023-03-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_work_3_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readermodel',
            name='books_instances',
        ),
    ]
