# Generated by Django 4.1.7 on 2023-03-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_work_3_app', '0002_remove_readermodel_books_instances'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readerbookmodel',
            old_name='book',
            new_name='book_instance',
        ),
    ]
