# Generated by Django 4.1.7 on 2023-03-13 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_work_3_app', '0002_bookmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInstanceModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('section', models.IntegerField()),
                ('status', models.CharField(choices=[('х', 'good'), ('с', 'bad')], max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory_work_3_app.bookmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReaderModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('ticket', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('passport_number', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('education', models.CharField(choices=[('p', 'primary'), ('s', 'secondary'), ('h', 'higher')], max_length=1)),
                ('is_has_academic_degree', models.BooleanField()),
                ('registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('books', models.ManyToManyField(to='laboratory_work_3_app.bookinstancemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReaderRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory_work_3_app.readermodel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory_work_3_app.roommodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReaderBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory_work_3_app.bookinstancemodel')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory_work_3_app.readermodel')),
            ],
        ),
    ]
