# Generated by Django 4.1.7 on 2023-03-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_work_3_app', '0004_readermodel_books_instances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstancemodel',
            name='status',
            field=models.CharField(choices=[('g', 'good'), ('b', 'bad')], max_length=1),
        ),
    ]
