# Generated by Django 4.1.2 on 2022-10-16 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id_car', models.IntegerField(primary_key=True, serialize=False)),
                ('registration_plate', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=20)),
                ('car_model', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='transport_Owner',
            fields=[
                ('id_owner', models.IntegerField(primary_key=True, serialize=False)),
                ('second_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('DOB', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers_license',
            fields=[
                ('id_license', models.IntegerField(primary_key=True, serialize=False)),
                ('number_license', models.CharField(max_length=10)),
                ('type_license', models.CharField(max_length=10)),
                ('date_start_license', models.DateField()),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.transport_owner')),
            ],
        ),
    ]
