# Generated by Django 4.1.2 on 2022-10-16 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id_owner_transport', models.IntegerField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('id_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.transport')),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.transport_owner')),
            ],
        ),
    ]
