# Generated by Django 4.1.2 on 2022-10-17 15:32

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0002_ownership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport_owner',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='transport_owner',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='transport_owner',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='transport_owner',
            name='email',
            field=models.CharField(default='work.email@mail.com', max_length=30),
        ),
        migrations.AddField(
            model_name='transport_owner',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='transport_owner',
            name='home_adress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transport_owner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='transport_owner',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='transport_owner',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='transport_owner',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='transport_owner',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='transport_owner',
            name='nationality',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transport_owner',
            name='passport_data',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transport_owner',
            name='password',
            field=models.CharField(default='65^I6M!Qkf1x', max_length=30),
        ),
        migrations.AddField(
            model_name='transport_owner',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='transport_owner',
            name='username',
            field=models.CharField(default='UserUser', max_length=30, unique=True, verbose_name='username'),
        ),
    ]
