# Generated by Django 4.1.2 on 2022-10-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_transport_owner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport_owner',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='username'),
        ),
    ]
