# Generated by Django 4.1.2 on 2022-10-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_transport_owner_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport_owner',
            name='username',
            field=models.CharField(max_length=40, unique=True, verbose_name='username'),
        ),
    ]
