# Generated by Django 4.1.2 on 2022-10-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_transport_owner_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport_owner',
            options={},
        ),
        migrations.AlterModelManagers(
            name='transport_owner',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='transport_owner',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='transport_owner',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='transport_owner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='transport_owner',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='transport_owner',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='transport_owner',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='transport_owner',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='transport_owner',
            name='password',
        ),
        migrations.RemoveField(
            model_name='transport_owner',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='transport_owner',
            name='username',
        ),
        migrations.AlterField(
            model_name='transport_owner',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
