# Generated by Django 4.1.3 on 2022-11-14 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ring", models.IntegerField()),
                ("ex1", models.CharField(max_length=100)),
                ("ex2", models.CharField(max_length=100)),
                ("ex3", models.CharField(max_length=100)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="CompParticipation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.competition",
                        verbose_name="Соревнование",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="DogOwner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("passport", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=100)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Expert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("education", models.CharField(max_length=256)),
                ("info", models.TextField(default=" ")),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score1", models.IntegerField()),
                ("score2", models.IntegerField()),
                ("score3", models.IntegerField()),
                (
                    "comp_participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.compparticipation",
                        verbose_name="Участие",
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.expert",
                        verbose_name="Эксперт",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpertCompetition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.competition",
                        verbose_name="Соревнование",
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.expert",
                        verbose_name="Эксперт",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exhibition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                (
                    "exhibition_type",
                    models.CharField(
                        choices=[
                            ("T1", "Монопородная выставка"),
                            ("T2", "Полипородная выставка"),
                        ],
                        max_length=2,
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_finish", models.DateField()),
                ("image", models.ImageField(upload_to="exhibition/static")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DogRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_paid", models.BooleanField(verbose_name="Оплата")),
                (
                    "dog",
                    smart_selects.db_fields.ChainedForeignKey(
                        auto_choose=True,
                        chained_field="owner",
                        chained_model_field="owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.dog",
                        verbose_name="Собака",
                    ),
                ),
                (
                    "exhibition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.exhibition",
                        verbose_name="Выставка",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.dogowner",
                        verbose_name="Хозяин",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dog",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.dogowner",
                verbose_name="Хозяин",
            ),
        ),
        migrations.CreateModel(
            name="Dismissed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.competition",
                        verbose_name="Соревнование",
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.dog",
                        verbose_name="Собака",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="compparticipation",
            name="dog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.dog",
                verbose_name="Собака",
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="exhibition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.exhibition",
                verbose_name="Выставка",
            ),
        ),
        migrations.CreateModel(
            name="ClubParticipation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.club",
                        verbose_name="Клуб",
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.dog",
                        verbose_name="Собака",
                    ),
                ),
            ],
        ),
    ]
