# Generated by Django 3.2.9 on 2022-02-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='bitrhday',
        ),
    ]
