# Generated by Django 3.2.9 on 2022-03-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_passenger_bitrhday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.CharField(default='2022-03-12 13:30', max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.CharField(default='2022-03-12 11:30', max_length=30),
        ),
    ]
