# Generated by Django 4.1.5 on 2023-01-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('led_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='type',
        ),
    ]
