# Generated by Django 4.1.4 on 2023-02-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211110_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='grade',
            field=models.CharField(blank=True, default='-', max_length=5),
        ),
    ]
