# Generated by Django 4.1.2 on 2022-10-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("table", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="ticket_number",
        ),
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name="passenger",
            name="passport_number",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
