site_name: Yor name 
site_url: https://mylab2.com

theme:
    name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
 - Лабораторная работа №2: index.md