# Generated by Django 4.0.1 on 2022-01-21 00:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchoice',
            unique_together={('user', 'city')},
        ),
    ]
