# Generated by Django 4.1.2 on 2022-10-20 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("avto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car_owner",
            name="date_of_birthday",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drivers_license",
            name="date_issue",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ownership",
            name="date_end",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ownership",
            name="date_start",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
