# Generated by Django 4.1.3 on 2022-11-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="carowner",
            name="date_of_birth",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="car_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_first_app.car",
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="finish_date",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="owner_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_first_app.carowner",
            ),
        ),
    ]
