# Generated by Django 4.1.3 on 2022-11-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_first_app",
            "0003_alter_car_color_alter_carowner_date_of_birth_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="carowner",
            name="cars",
            field=models.ManyToManyField(
                through="project_first_app.Ownership", to="project_first_app.car"
            ),
        ),
    ]
