# Generated by Django 4.1.2 on 2022-11-20 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('photo_url', models.CharField(max_length=100)),
                ('photo_image_url', models.CharField(max_length=100)),
                ('photo_width', models.IntegerField()),
                ('photo_height', models.IntegerField()),
                ('photo_description', models.CharField(max_length=200)),
                ('photographer_username', models.CharField(max_length=100)),
                ('photographer_first_name', models.CharField(max_length=100)),
                ('photographer_last_name', models.CharField(max_length=100)),
                ('blur_hash', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LikePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex', models.CharField(max_length=10)),
                ('keyword', models.CharField(max_length=30)),
                ('red', models.IntegerField(blank=True, null=True)),
                ('blue', models.IntegerField(blank=True, null=True)),
                ('green', models.IntegerField(blank=True, null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.photo')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='images.collection')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='images.photo')),
            ],
        ),
    ]
