# Generated by Django 4.1.2 on 2022-11-20 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likephoto',
            unique_together={('photo', 'user')},
        ),
    ]
