site_name: READ ME FIRST "school"
nav:
 - Home: index.md
 - Api:
     - "/admin": api/admin.md
     - "create/users": api/users.md
     - "change/users/": api/change_users.md
     - "create/class": api/class.md
     - "change/class/": api/change_class.md
     - "create/user_class": api/user_class.md
     - "change/user_class/": api/change_user_class.md

theme:
 name: material