# Generated by Django 4.1.2 on 2022-10-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
