# Generated by Django 4.1.2 on 2022-10-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_alter_car_color_alter_carowner_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='own',
            name='end_own_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
