# Generated by Django 4.1.2 on 2022-11-30 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owning',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owning_car', to=settings.AUTH_USER_MODEL),
        ),
    ]
