# Generated by Django 4.1.7 on 2023-03-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='addres',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='nationality',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='passport_num',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
