site_name: Konev Anton K33402


nav:
  - Home: index.md
  - Лабораторные работы:
      - Лабораторная работа №1: lab_1.md
      - Лабораторная работа №2: lab_2.md
      - Лабораторная работа №3: lab_3.md
  - Практические работы:
      - Практическая работа №3.1: prac_3.1.md

