# Generated by Django 4.1.7 on 2023-02-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Driver',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='licence',
            old_name='driver',
            new_name='owner',
        ),
    ]
