# Generated by Django 4.1.7 on 2023-03-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merofond", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["datetime"]},
        ),
        migrations.RenameField(
            model_name="event",
            old_name="type",
            new_name="event_type",
        ),
        migrations.AlterField(
            model_name="location",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
