# Generated by Django 4.1.5 on 2023-01-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ownership',
            name='start_end_date_correct',
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='start_end_date_check', violation_error_message='Start date must be earlier than end date.'),
        ),
    ]
