# Generated by Django 4.1.5 on 2023-01-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_carownsershipmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarOwnsershipModel',
        ),
    ]
