# Generated by Django 4.1.5 on 2023-01-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0005_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
    ]
