# Generated by Django 4.1.1 on 2022-10-14 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('passport', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Номер паспорта')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Название отеля')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('owner', models.CharField(max_length=255, verbose_name='Владелец отеля')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('number_room', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер комнаты')),
                ('type_room', models.CharField(max_length=100, verbose_name='Описание комнаты')),
                ('beds', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество спальных мест')),
                ('room_price', models.PositiveIntegerField(verbose_name='Стоимость номера')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель')),
            ],
            options={
                'unique_together': {('number_room', 'hotel')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('arrival_date', models.DateField(verbose_name='Дата заезда')),
                ('departure_date', models.DateField(verbose_name='Дата выезда')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость проживания')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.guest', verbose_name='Гость')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.room')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата заезда')),
                ('date_end', models.DateField(verbose_name='Дата выезда')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('rate', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Оценка')),
                ('sing_author', models.CharField(max_length=30, verbose_name='Укажите ваш ник')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.reservation', verbose_name='Код бронирования')),
            ],
        ),
    ]
