# Generated by Django 4.1.1 on 2022-10-16 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_reservation_hotel_alter_reservation_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hotel', 'number_room')},
        ),
    ]
