# Generated by Django 4.1.2 on 2022-10-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id_car", models.AutoField(primary_key=True, serialize=False)),
                ("state_num", models.CharField(max_length=15)),
                ("brand", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=20)),
                ("color", models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="CarOwner",
            fields=[
                ("id_owner", models.AutoField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=30)),
                ("first_name", models.CharField(max_length=30)),
                ("birth_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[
                ("id_owner_car", models.AutoField(primary_key=True, serialize=False)),
                ("date_start", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
                (
                    "id_car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_first_app.car",
                    ),
                ),
                (
                    "id_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_first_app.carowner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverLicense",
            fields=[
                ("id_license", models.AutoField(primary_key=True, serialize=False)),
                ("license_num", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=10)),
                ("issue_date", models.DateTimeField()),
                (
                    "id_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_first_app.carowner",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="owners",
            field=models.ManyToManyField(
                through="project_first_app.Ownership", to="project_first_app.carowner"
            ),
        ),
    ]
