# Generated by Django 4.1.2 on 2022-10-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carowner",
            name="birth_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="issue_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="date_end",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="date_start",
            field=models.DateField(),
        ),
    ]
