# Generated by Django 4.1.2 on 2022-10-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0002_alter_carowner_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carowner",
            name="birth_date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="date_end",
            field=models.DateField(blank=True),
        ),
    ]
