# Generated by Django 4.1.2 on 2022-10-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_first_app",
            "0003_alter_carowner_birth_date_alter_ownership_date_end",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownership",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
    ]
