# Generated by Django 4.1.2 on 2022-10-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0004_alter_ownership_date_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carowner",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
