# Generated by Django 4.1.3 on 2022-11-26 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auto",
            fields=[
                ("id_auto", models.IntegerField(primary_key=True, serialize=False)),
                ("state_number", models.CharField(max_length=15)),
                ("mark_auto", models.CharField(max_length=30)),
                ("model_auto", models.CharField(max_length=30)),
                ("color_auto", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AutoOwner",
            fields=[
                ("id_owner", models.IntegerField(primary_key=True, serialize=False)),
                ("last_name", models.CharField(max_length=30)),
                ("first_name", models.CharField(max_length=30)),
                ("birth_day", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[
                (
                    "id_owner_auto",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                (
                    "id_auto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car",
                        to="car_app.auto",
                    ),
                ),
                (
                    "id_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to="car_app.autoowner",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrivingLicense",
            fields=[
                ("id_license", models.IntegerField(primary_key=True, serialize=False)),
                ("license_number", models.CharField(max_length=10)),
                ("category", models.CharField(max_length=10)),
                ("date_of_license", models.DateField()),
                (
                    "id_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_owner",
                        to="car_app.autoowner",
                    ),
                ),
            ],
        ),
    ]
