# Generated by Django 4.1.3 on 2022-11-12 22:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField(verbose_name="Дата заезда")),
                ("date_end", models.DateField(verbose_name="Дата выезда")),
                (
                    "total_price",
                    models.PositiveIntegerField(verbose_name="Стоимость проживания"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                ("last_name", models.CharField(max_length=30, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=30, verbose_name="Имя")),
                (
                    "passport",
                    models.CharField(
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Номер паспорта",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Название отеля",
                    ),
                ),
                (
                    "owner",
                    models.CharField(max_length=50, verbose_name="Владелец отеля"),
                ),
                (
                    "address",
                    models.CharField(max_length=100, verbose_name="Адрес отеля"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Номер комнаты")),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Описание номера"),
                ),
                (
                    "type_room",
                    models.CharField(
                        choices=[
                            ("S", "Стандарт"),
                            ("С", "Комфорт"),
                            ("L", "Люкс"),
                            ("F", "Семейный"),
                            ("P", "Президентский"),
                            ("A", "Апартаменты"),
                        ],
                        max_length=1,
                        verbose_name="Тип номера",
                    ),
                ),
                (
                    "beds",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество спальных мест",
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Стоимость номера")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.hotel",
                        verbose_name="Отель",
                    ),
                ),
            ],
            options={
                "unique_together": {("hotel", "number")},
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(max_length=30, verbose_name="Укажите ваш ник"),
                ),
                (
                    "rate",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Оценка",
                    ),
                ),
                ("date_start", models.DateField(verbose_name="Дата заезда")),
                ("date_end", models.DateField(verbose_name="Дата выезда")),
                ("text", models.TextField(verbose_name="Комментарий")),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotels.booking",
                        verbose_name="Код бронирования",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hotels.guest"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hotels.hotel",
                verbose_name="Отель",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hotels.room"
            ),
        ),
    ]
