# Generated by Django 4.1.3 on 2022-11-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.CharField(max_length=1000, verbose_name="Описание номера"),
        ),
    ]
