# Generated by Django 4.1.2 on 2022-10-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hotel',
        ),
    ]
