# Generated by Django 4.1.4 on 2022-12-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee", old_name="passport", new_name="id_emp",
        ),
    ]
