# Generated by Django 4.1.4 on 2022-12-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0003_remove_room_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="number_booking",
            field=models.AutoField(
                max_length=100,
                primary_key=True,
                serialize=False,
                verbose_name="id_booking",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status_payment",
            field=models.CharField(
                choices=[("0", "Не оплачено"), ("1", "Оплачено")],
                max_length=20,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
