site_name: Airport
nav:
  - Home: index.md
  - Employees:
      - "list of employees": user/employee.md
  - API:
      - "api/airplanes": api/airplanes.md
      - "api/schedule": api/schedule.md
      - "api/flights": api/flights.md
      - "api/airline_admin": api/airline_admin.md
      - "api/transit": api/transit.md

theme:
  name: windmill