site_name: Описание сервиса "Warriors"
nav:
 - Home: README/README.md
 - Professions:
     - "mining engineering": professions/mining_engineering.md
     - "picking herbs": professions/picking_herbs.md
 - Skills:
     - "mining engineering": skills/smart.md
     - "picking herbs": skills/fast.md
 - Api:
     - "general description": api/general_description.md
     - "endpoints": api/endpoints.md
     - "authorization": api/authorization.md

theme:
 name: material