# Generated by Django 4.1.3 on 2022-11-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0002_comment_rating_plannedconference_themes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plannedconference", options={"ordering": ["start_date"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
