# Generated by Django 4.1.3 on 2022-11-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0004_alter_comment_options_alter_comment_date"),
    ]

    operations = [
        migrations.AlterModelOptions(name="comment", options={"ordering": ["-date"]},),
        migrations.AlterField(
            model_name="registeredconference",
            name="results",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
