# Generated by Django 4.0 on 2021-12-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('teacher', 'я учитель'), ('student', 'я студент')], max_length=10, null=True),
        ),
    ]