# Generated by Django 4.0 on 2021-12-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks_app', '0002_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomework',
            name='done_task',
            field=models.TextField(blank=True, null=True),
        ),
    ]