# Generated by Django 4.0 on 2022-01-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks_app', '0004_homework_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]