# Generated by Django 4.1.7 on 2023-03-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='img/default_ev.png', upload_to='img/'),
            preserve_default=False,
        ),
    ]
