# Generated by Django 4.1.7 on 2023-03-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='seats_count',
            new_name='max_count',
        ),
    ]
