# Generated by Django 4.1.7 on 2023-03-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_rename_seats_count_location_max_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_meet_type',
        ),
    ]
