# Generated by Django 4.1.7 on 2023-03-14 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0004_remove_event_event_meet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 14)),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.time(23, 59, 59, 999999)),
        ),
        migrations.AddField(
            model_name='location',
            name='place_name',
            field=models.CharField(default='none', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='img/profile.png', upload_to='img'),
        ),
    ]
