# Generated by Django 4.1.7 on 2023-03-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0005_remove_category_image_event_date_event_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
