# Generated by Django 4.1.2 on 2022-10-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr2_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
