# Generated by Django 4.1.2 on 2022-10-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr2_1', '0002_alter_ownership_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='drivinglicense',
            name='date_of_issue',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='birthday_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
