site_name: Korobkovskii Vadim, K33422

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Знакомство: index.md
  - Лабораторная работа №1: lab_work1.md
