site_name: Korobkovskii Vadim, K33422

theme:
  name: material

markdown_extensions:
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Знакомство: index.md
  - Лабораторная работа №1: lab_work1.md
  - Лабораторная работа №2: lab_work2.md
