# Generated by Django 4.1.2 on 2022-11-15 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_drivinglicense_owner_id_alter_ownership_car_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicense',
            name='owner_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license_owner_guy', related_query_name='license_owner', to='project.owner'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_cars', related_query_name='hold_car', to='project.car'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_owners', related_query_name='hold_owner', to='project.owner'),
        ),
    ]
