# Generated by Django 4.0.3 on 2022-03-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='online_store.ProductsOfOrder', to='online_store.product'),
        ),
        migrations.DeleteModel(
            name='UserOfOrder',
        ),
    ]
