# Generated by Django 4.1.5 on 2023-01-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carowner',
            options={'verbose_name': 'Car owner', 'verbose_name_plural': 'Car owners'},
        ),
        migrations.AlterField(
            model_name='carowner',
            name='ownership_id',
            field=models.ManyToManyField(blank=True, null=True, to='project_first_app.ownership'),
        ),
    ]
