# Generated by Django 4.1.4 on 2022-12-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr3app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=models.CharField(default='default_user.png', max_length=100, null=True),
        ),
    ]
