# Generated by Django 4.1.4 on 2023-01-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr3app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=models.ImageField(default='default_user.png', max_length=1000, null=True, upload_to='images'),
        ),
    ]
