# Generated by Django 4.1.4 on 2023-01-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr3app', '0004_alter_user_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolledevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
