# Generated by Django 4.1.4 on 2023-01-10 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lr3app', '0005_alter_userenrolledevent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenrolledevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lr3app.event'),
        ),
    ]
