# Generated by Django 4.1.2 on 2022-11-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Почта/E-mail'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер телефона/Phone number'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Почта/E-mail'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_passport',
            field=models.CharField(max_length=30, unique=True, verbose_name="Серия и номер пасспорта хозяина/Owner's passport number"),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер телефона/Phone number'),
        ),
    ]
