# Generated by Django 4.1.2 on 2022-10-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Сonference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=300)),
                ('place_description', models.TextField()),
                ('descriptions', models.TextField()),
                ('period', models.DurationField()),
                ('conditions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User_confirence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Conferences.сonference')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Conferences.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Conferences.сonference')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Conferences.user')),
            ],
        ),
    ]
