# Generated by Django 4.1.2 on 2022-10-20 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
