# Generated by Django 4.1.2 on 2022-10-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conferences', '0002_remove_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сonference',
            name='period',
        ),
        migrations.AddField(
            model_name='сonference',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='сonference',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
