# Generated by Django 4.1.2 on 2022-10-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conferences', '0003_remove_сonference_period_сonference_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сonference',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
