# Generated by Django 4.1.2 on 2022-10-21 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conferences', '0004_alter_сonference_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rank',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
