# Generated by Django 4.1.2 on 2022-10-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Conferences', '0006_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
