# Generated by Django 4.1.2 on 2022-12-04 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(choices=[('h', 'haski'), ('t', 'terrier'), ('b', 'bulldog')], max_length=1)),
                ('age', models.IntegerField()),
                ('family', models.CharField(max_length=1000)),
                ('owner_data', models.CharField(max_length=1000)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dogsapp.club')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('mono', 'mono-breed'), ('poly', 'poly-breed')], max_length=4)),
                ('participants', models.ManyToManyField(related_name='show_participants', to='dogsapp.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(choices=[('h', 'haski'), ('t', 'terrier'), ('b', 'bulldog')], max_length=1)),
                ('experts', models.ManyToManyField(blank=True, null=True, related_name='ring_experts', to='dogsapp.expert')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogsapp.show')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.CharField(choices=[('g', 'gold'), ('s', 'silver'), ('b', 'bronze')], max_length=1)),
                ('vaccinated', models.DateField()),
                ('dismissed', models.BooleanField()),
                ('final_grade', models.IntegerField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogsapp.participant')),
                ('rings', models.ManyToManyField(blank=True, null=True, to='dogsapp.ring')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(related_name='club_members', to='dogsapp.participant'),
        ),
    ]
