# Generated by Django 4.1.1 on 2022-10-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pr_1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transport_owner",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="transport_owner",
            name="username",
            field=models.CharField(
                max_length=150, unique=True, verbose_name="username"
            ),
        ),
    ]
