# Generated by Django 4.1.5 on 2023-01-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_alter_carowner_options_alter_carowner_ownership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='ownership_id',
            field=models.ManyToManyField(blank=True, to='project_first_app.ownership'),
        ),
    ]
