# Generated by Django 4.1.5 on 2023-01-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_alter_carowner_ownership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
