# Generated by Django 4.1.2 on 2022-11-07 15:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submit', models.DateField(default=datetime.datetime(2022, 11, 7, 15, 48, 1, 657634, tzinfo=datetime.timezone.utc))),
                ('text', models.CharField(blank=True, max_length=1000)),
                ('grade', models.IntegerField(blank=True, choices=[(5, 5), (4, 4), (3, 3), (2, 2)])),
            ],
        ),
        migrations.CreateModel(
            name='TeacherHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('info', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='study_class',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.AddField(
            model_name='teacherhomework',
            name='study_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='homework_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hw_app.teacherhomework'),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='case',
            field=models.ManyToManyField(through='hw_app.StudentHomework', to='hw_app.teacherhomework'),
        ),
    ]
