# Generated by Django 4.1.2 on 2022-11-07 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hw_app', '0002_studenthomework_teacherhomework_student_study_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='date_submit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teacherhomework',
            name='study_class',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
