# Generated by Django 4.1.2 on 2022-11-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_app', '0004_alter_studenthomework_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(5, 5), (4, 4), (3, 3), (2, 2)], null=True),
        ),
    ]
