# Generated by Django 4.1.2 on 2022-10-12 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_name', models.CharField(max_length=50, verbose_name='conference')),
                ('topic', models.CharField(blank=True, choices=[('business', 'business'), ('design', 'design'), ('physics', 'physics')], max_length=10, verbose_name='topic')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('description', models.CharField(max_length=200, verbose_name='conference description')),
                ('location_description', models.CharField(max_length=200, verbose_name='location description')),
                ('terms', models.CharField(max_length=1000, verbose_name='participation terms')),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='speaker')),
            ],
            options={
                'verbose_name': 'conference',
                'verbose_name_plural': 'conferences',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='comment author')),
                ('conf_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf_app.conference', verbose_name='conference')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
