# Generated by Django 4.1.2 on 2022-10-15 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='conf_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='conf_name',
            new_name='name',
        ),
    ]
