# Generated by Django 4.1.2 on 2022-10-15 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conf_app', '0005_remove_conference_speaker_conference_speaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='speaker',
        ),
        migrations.AddField(
            model_name='conference',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='speaker'),
        ),
    ]
