# Generated by Django 4.1.1 on 2022-10-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_owner',
            name='birth_day',
            field=models.DateField(null=True),
        ),
    ]
