# Generated by Django 4.1.1 on 2022-10-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_alter_car_owner_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_owner',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car_owner',
            name='nationality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car_owner',
            name='passport',
            field=models.IntegerField(null=True),
        ),
    ]
