# Generated by Django 4.1.2 on 2022-10-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
