# Generated by Django 4.1.2 on 2022-10-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0002_subject_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='date_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='date_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='task_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
