# Generated by Django 4.1.6 on 2023-02-21 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_model", models.CharField(max_length=100, null=True)),
                ("number", models.IntegerField(null=True, unique=True)),
                (
                    "car_type",
                    models.CharField(
                        choices=[
                            ("Circuit", "Circuit car"),
                            ("Rally", "Rally car"),
                            ("Endurance", "Rally car"),
                            ("Drag", "Drag car"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("speed", models.IntegerField(null=True)),
                ("weight", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("race_date", models.DateField(null=True)),
                (
                    "race_type",
                    models.CharField(
                        choices=[
                            ("Circuit", "Circuit race"),
                            ("Rally", "Rally race"),
                            ("Endurance", "Endurance race"),
                            ("Drag", "Drag race"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("length", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Racer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("surname", models.CharField(max_length=100, null=True)),
                ("birthday", models.DateField(null=True)),
                ("team", models.CharField(max_length=100, null=True)),
                ("country", models.CharField(max_length=100, null=True)),
                (
                    "driver_class",
                    models.CharField(
                        choices=[
                            ("Circuit", "Circuit racer"),
                            ("Rally", "Rally racer"),
                            ("Endurance", "Rally racer"),
                            ("Drag", "Drag racer"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("experience", models.IntegerField(null=True)),
                ("decription", models.CharField(max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.IntegerField(blank=True, null=True)),
                (
                    "car",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="race_app.car",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="race_app.race",
                    ),
                ),
                (
                    "racer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="race_app.racer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="race",
            name="registrations",
            field=models.ManyToManyField(
                blank=True, through="race_app.Registration", to="race_app.racer"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("Вопрос о сотрудничестве", "Cooperation"),
                            ("Вопрос о гонках", "About race"),
                            ("Иное", "Other"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "rate",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="race_app.race",
                    ),
                ),
                (
                    "racer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="race_app.racer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="racer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="race_app.racer",
            ),
        ),
    ]
