site_name: Описание сервиса "Library"
nav:
  - Home: index.md
  - API: 
    - "readers[GET]": api/readers.md
    - "books[GET]": api/books.md
    - "library[GET]": api/library.md
    - "rooms[GET]": api/rooms.md
    - "one reader[GET, PATCH, DELETE]": api/single_reader.md
    - "one book[GET, PATCH, DELETE]": api/single_book.md
    - "edit library[GET, PATCH, DELETE]": api/edit_library.md
    - "one room[GET, PATCH, DELETE]": api/single_room.md
    - "create reader[POST]": api/create_reader.md
    - "create book[POST]": api/create_book.md
    - "create room[POST]": api/create_room.md
  - Registration:
    - "auth/users[POST]": registration/user.md
    - "auth/users/me[POST]": registration/login.md
    - "auth/users/me[PATCH]" : registration/edit.md

theme:
  name: windmill-dark
