# Generated by Django 4.1.2 on 2022-10-29 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=15)),
                ('brand', models.CharField(choices=[('RENAULT', 'Renault'), ('VOLKSWAGEN', 'Volkswagen'), ('KIA', 'Kia'), ('SKODA', 'Skoda'), ('TOYOTA', 'Toyota'), ('PEUGEOT', 'Peugeot')], max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthdate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_fin', models.DateField(null=True)),
                ('id_auto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_first_app.car')),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_first_app.owner')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='case',
            field=models.ManyToManyField(through='project_first_app.Owning', to='project_first_app.car'),
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_license', models.CharField(max_length=10)),
                ('type_license', models.CharField(choices=[('M', 'm'), ('A', 'a'), ('B', 'b'), ('BE', 'be'), ('C', 'c'), ('CE', 'ce'), ('D', 'd'), ('DE', 'de'), ('TM', 'tm'), ('TB', 'tb')], max_length=10)),
                ('date_license', models.DateField()),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_first_app.owner')),
            ],
        ),
    ]
