# Generated by Django 4.1.2 on 2022-10-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='id_owner',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='owning',
            old_name='id_auto',
            new_name='car_id',
        ),
        migrations.RenameField(
            model_name='owning',
            old_name='id_owner',
            new_name='owner_id',
        ),
    ]
