# Generated by Django 4.1.2 on 2022-10-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0003_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='recommend',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=3, verbose_name='recommend'),
            preserve_default=False,
        ),
    ]
