# Generated by Django 4.1.2 on 2022-10-15 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conf_app', '0004_conference_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='speaker',
        ),
        migrations.AddField(
            model_name='conference',
            name='speaker',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='speaker'),
        ),
    ]
