# Generated by Django 4.1.4 on 2022-12-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booksonhands",
            name="date_register",
        ),
    ]
