# Generated by Django 4.1.4 on 2022-12-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0002_remove_booksonhands_date_register"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reader",
            name="registration_date",
        ),
        migrations.AddField(
            model_name="booksonhands",
            name="date_register",
            field=models.DateField(blank=True, null=True, verbose_name="Дата выдачи"),
        ),
    ]
