# Generated by Django 4.1.4 on 2022-12-28 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0003_remove_reader_registration_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reader",
            name="passport",
        ),
        migrations.AddField(
            model_name="reader",
            name="reader_hall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="library_app.hall",
                verbose_name="Зал",
            ),
        ),
    ]
