# Generated by Django 4.1.2 on 2022-12-04 00:05

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('card_number', models.IntegerField(blank=True, null=True, verbose_name='Читательский билет')),
                ('first_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('passport', models.CharField(blank=True, max_length=15, null=True, verbose_name='Паспорт')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Телефон')),
                ('education', models.CharField(blank=True, choices=[('Среднее общее', 'Среднее общее'), ('Среднее специальное', 'Среднее специальное'), ('Высшее', 'Высшее'), ('Неоконченное высшее', 'Неоконченное высшее'), ('Неоконченное среднее', 'Неоконченное среднее')], default='-', max_length=4000, null=True, verbose_name='Образование')),
                ('degree', models.BooleanField(blank=True, default=False, null=True, verbose_name='Ученая степень')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800, verbose_name='Название')),
                ('authors', models.CharField(max_length=5000, verbose_name='Автор(ы)')),
                ('publisher', models.CharField(max_length=79, verbose_name='Издательство')),
                ('publication_year', models.IntegerField(verbose_name='Год издания')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('book_cypher', models.CharField(max_length=50, verbose_name='Шифр')),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id_copy', models.AutoField(primary_key=True, serialize=False, verbose_name='ID_экземпляра')),
                ('section', models.CharField(max_length=20, verbose_name='Раздел')),
                ('code', models.CharField(max_length=20, verbose_name='Артикул')),
                ('year', models.IntegerField(verbose_name='Год издания')),
                ('condition', models.CharField(choices=[('х', 'хорошее'), ('у', 'удовлетворительное'), ('с', 'старое')], max_length=1, verbose_name='Состояние экземпляра')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='Книга')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
            ],
        ),
        migrations.CreateModel(
            name='ReaderBook',
            fields=[
                ('id_rb', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='номер выдачи')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='Книга')),
                ('id_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.copy', verbose_name='Id_ex')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Читатель')),
            ],
        ),
        migrations.CreateModel(
            name='BookInHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Число экземпляров')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book', verbose_name='Книга')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.hall', verbose_name='Зал')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_hall',
            field=models.ManyToManyField(related_name='BokkCopy', through='library_app.BookInHall', to='library_app.hall', verbose_name='Зал'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_reader',
            field=models.ManyToManyField(through='library_app.ReaderBook', to=settings.AUTH_USER_MODEL, verbose_name='Читатель'),
        ),
        migrations.AddField(
            model_name='reader',
            name='reader_book',
            field=models.ManyToManyField(through='library_app.ReaderBook', to='library_app.book', verbose_name='Книга'),
        ),
        migrations.AddField(
            model_name='reader',
            name='reader_hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.hall', verbose_name='Зал'),
        ),
        migrations.AddField(
            model_name='reader',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
