# Generated by Django 4.1.3 on 2022-11-28 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_num', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('owner_car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prac.car')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prac.owner')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_id', models.IntegerField(primary_key=True, serialize=False)),
                ('license_num', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('start_date_license', models.DateField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prac.owner')),
            ],
        ),
    ]
