# Generated by Django 4.1.7 on 2023-03-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
