# Generated by Django 4.1.7 on 2023-03-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_alter_owner_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicence',
            name='license_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.car'),
        ),
        migrations.AlterField(
            model_name='property',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.owner'),
        ),
    ]
