site_name: Konev Anton, K33402

theme:
  name: mkdocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
nav:
 - Знакомство: index.md
 - Лабораторная работа №1: LW_1.md
 - Лабораторная работа №2: LW_2.md