# Generated by Django 3.2.9 on 2021-11-10 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211110_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='answer',
            new_name='submission',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='grade',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
