# Generated by Django 4.1.4 on 2022-12-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinvest", "0002_marketentry_marketrequest_marketrequestdeal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketrequestdeal",
            name="ts_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
