# Generated by Django 4.1.4 on 2022-12-21 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinvest", "0003_marketrequestdeal_ts_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketrequestdeal",
            name="ts_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 21, 17, 52, 8, 395210, tzinfo=datetime.timezone.utc)
            ),
        ),
    ]
