# Generated by Django 4.1.4 on 2022-12-21 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tinvest", "0004_alter_marketrequestdeal_ts_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketrequestdeal",
            name="ts_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
