# Generated by Django 4.2 on 2023-04-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='plane',
        ),
        migrations.AlterField(
            model_name='flight',
            name='transit_land',
            field=models.ManyToManyField(blank=True, related_name='flight', to='airport_app.transitlanding'),
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight', to='airport_app.plane'),
        ),
    ]
