# Generated by Django 4.2 on 2023-04-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0002_remove_flight_plane_alter_flight_transit_land_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('s', 'steward'), ('c', 'commander'), ('p', 'second pilot'), ('n', 'navigator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='transit_land',
            field=models.ManyToManyField(blank=True, null=True, related_name='flight', to='airport_app.transitlanding'),
        ),
    ]
