# Generated by Django 4.1.7 on 2023-02-22 17:25

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.ClientManager()),
            ],
        ),
    ]
