# Generated by Django 4.1.7 on 2023-02-26 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_board_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AcademicDiscipline',
            new_name='AcademicDisciplineModel',
        ),
        migrations.CreateModel(
            name='EducationalJournalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(verbose_name='Mark')),
                ('homework_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_board_app.homeworkmodel')),
                ('student_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_board_app.studentmodel')),
            ],
        ),
    ]
