# Generated by Django 4.1.7 on 2023-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_board_app', '0002_rename_academicdiscipline_academicdisciplinemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseusermodel',
            name='second_name',
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
