# Generated by Django 4.1.7 on 2023-02-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_board_app', '0003_remove_baseusermodel_second_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicdisciplinemodel',
            name='teacher_uuid',
        ),
    ]
