# Generated by Django 4.1.7 on 2023-02-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_board_app', '0004_remove_academicdisciplinemodel_teacher_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkmodel',
            name='teacher',
        ),
    ]
