# Generated by Django 4.1.7 on 2023-03-11 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_board_app', '0005_remove_homeworkmodel_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitHomeworkTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=1000)),
                ('homework_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_board_app.homeworkmodel')),
            ],
        ),
    ]
