# Generated by Django 4.1.7 on 2023-03-11 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homework_board_app', '0006_submithomeworktaskmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submithomeworktaskmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='submithomeworktaskmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
