# Generated by Django 4.1.7 on 2023-03-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_board_app', '0007_remove_submithomeworktaskmodel_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationalJournalModel',
        ),
    ]
