# Generated by Django 4.1.7 on 2023-03-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_board_app', '0009_educationaljournalmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationalJournalModel',
        ),
    ]
