# Generated by Django 4.1.7 on 2023-03-11 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_board_app', '0010_delete_educationaljournalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalJournalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(verbose_name='Mark')),
                ('homework_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_board_app.homeworkmodel')),
                ('submit_homework_task_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_board_app.submithomeworktaskmodel')),
            ],
        ),
    ]
