# Generated by Django 4.1.7 on 2023-03-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework_board_app', '0012_remove_educationaljournalmodel_homework_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='submithomeworktaskmodel',
            name='student_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='homework_board_app.studentmodel'),
            preserve_default=False,
        ),
    ]
