site_name: Лабораторные работы
theme:
    name: material

nav:
  - Информация: "index.md"
  - Лабораторная работа №1: "pages/lab1.md"
  - Лабораторная работа №2: "pages/lab2.md"
  - Лабораторная работа №3: "pages/lab3.md"
