# Generated by Django 4.1.3 on 2022-11-26 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cars_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car_owner",
            options={},
        ),
        migrations.AlterModelManagers(
            name="car_owner",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="car_owner",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="car_owner",
            name="email",
        ),
        migrations.RemoveField(
            model_name="car_owner",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="car_owner",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="car_owner",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="car_owner",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="car_owner",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="car_owner",
            name="password",
        ),
        migrations.RemoveField(
            model_name="car_owner",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="car_owner",
            name="username",
        ),
        migrations.AlterField(
            model_name="driver_license",
            name="id_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cars_app.car_owner"
            ),
        ),
        migrations.AlterField(
            model_name="ownerdhip",
            name="id_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cars_app.car_owner"
            ),
        ),
    ]
