# Generated by Django 4.1.3 on 2022-12-25 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0003_alter_driver_license_id_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdhip',
            name='id_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='cars_app.car_owner'),
        ),
    ]
