# Generated by Django 4.1.7 on 2023-03-12 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='skillofwarrior',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skillofwarrior',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warriors_app.skill'),
        ),
        migrations.AlterField(
            model_name='skillofwarrior',
            name='warrior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warriors_app.warrior'),
        ),
        migrations.AlterField(
            model_name='warrior',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='warrior',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='warrior',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warriors_app.profession'),
        ),
        migrations.AlterField(
            model_name='warrior',
            name='race',
            field=models.CharField(choices=[('s', 'student'), ('d', 'developer'), ('t', 'teamlead')], max_length=1),
        ),
        migrations.AlterField(
            model_name='warrior',
            name='skill',
            field=models.ManyToManyField(related_name='warrior_skills', through='warriors_app.SkillOfWarrior', to='warriors_app.skill'),
        ),
    ]
