# Generated by Django 4.1.3 on 2022-11-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorship",
            name="order_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
