# Generated by Django 4.1.2 on 2022-10-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
