# Generated by Django 4.1.5 on 2023-01-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('flight_type', models.CharField(choices=[('Departure', 'Departure'), ('Arrival', 'Arrival')], default='Departure', max_length=20)),
                ('gate', models.CharField(max_length=20)),
                ('airline', models.CharField(max_length=100)),
                ('fligt_number', models.CharField(max_length=10)),
                ('source_airport_code', models.CharField(max_length=10)),
                ('destination_airport_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, default='4a84701d-216b-4db5-a5f6-5b69f85fe6d7', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='api_url',
            field=models.CharField(blank=True, default='https://airlabs.co/api/v9/airports?', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.CheckConstraint(check=models.Q(('arrival__gt', models.F('departure'))), name='departure_arrival_check', violation_error_message='Departure must be earlier than arrival.'),
        ),
    ]
