# Generated by Django 4.1.5 on 2023-01-20 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_flight_max_reservations_flight_reservations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='reservators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
