# Generated by Django 4.1.5 on 2023-01-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_flight_reservators'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flight',
            name='can_reserve_check',
        ),
    ]
