# Generated by Django 4.1.5 on 2023-01-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_flight_can_reserve_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='reservations',
        ),
    ]
