# Generated by Django 4.1.5 on 2023-01-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_flight_reviews_review_flight_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='flight_pk',
            new_name='flight',
        ),
    ]
