# Generated by Django 4.1.3 on 2022-11-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='id_Dar',
            new_name='id_Car',
        ),
    ]
