# Generated by Django 4.1.7 on 2023-02-23 14:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "passport",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Паспортные данные"
                    ),
                ),
                ("full_name", models.CharField(max_length=120, verbose_name="ФИО")),
                ("age", models.IntegerField(default=18, verbose_name="Возраст")),
                (
                    "education",
                    models.CharField(
                        choices=[("СПО", "среднее профессиональное"), ("ВО", "высшее")],
                        max_length=3,
                        verbose_name="Образование",
                    ),
                ),
                ("experience", models.IntegerField(verbose_name="Стаж работы в годах")),
                (
                    "in_crew",
                    models.IntegerField(
                        default=0, verbose_name="Состоит в экипаже под номером"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Airplane",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "tail_number",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="Номер самолета"
                    ),
                ),
                ("type", models.CharField(max_length=20, verbose_name="Тип")),
                ("seats", models.IntegerField(verbose_name="Число мест")),
                (
                    "velocity",
                    models.IntegerField(verbose_name="Скорость полёта (км/ч)"),
                ),
                (
                    "airline",
                    models.CharField(max_length=30, verbose_name="Авиакомпания"),
                ),
                (
                    "under_maintenance",
                    models.BooleanField(default=False, verbose_name="В ремонте"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transit",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "destination",
                    models.CharField(max_length=25, verbose_name="Пункт пересадки"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightAsScheduled",
            fields=[
                (
                    "number",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Номер рейса",
                    ),
                ),
                (
                    "distance",
                    models.IntegerField(
                        verbose_name="Расстояние до пункта назначения в км"
                    ),
                ),
                (
                    "departure",
                    models.CharField(max_length=25, verbose_name="Пункт вылета"),
                ),
                (
                    "arrival",
                    models.CharField(max_length=25, verbose_name="Пункт назначения"),
                ),
                (
                    "completed",
                    models.IntegerField(verbose_name="Количество совершённых рейсов"),
                ),
                (
                    "transit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport_app.transit",
                        verbose_name="Транзит",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("crew", models.IntegerField(verbose_name="Экипаж на борту")),
                (
                    "tickets_sold",
                    models.IntegerField(verbose_name="Количество проданных билетов"),
                ),
                ("departure_date", models.DateField(verbose_name="Дата вылета")),
                ("departure_time", models.TimeField(verbose_name="Время вылета")),
                ("arrival_date", models.DateField(verbose_name="Дата прилета")),
                ("arrival_time", models.TimeField(verbose_name="Время прилета")),
                (
                    "transit_arrival_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата транзитной посадки"
                    ),
                ),
                (
                    "transit_arrival_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время транзитной посадки"
                    ),
                ),
                (
                    "transit_departure_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата вылета из транзита"
                    ),
                ),
                (
                    "transit_departure_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время вылета из транзита"
                    ),
                ),
                (
                    "number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport_app.flightasscheduled",
                        verbose_name="Номер рейса",
                    ),
                ),
                (
                    "plane_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="airport_app.airplane",
                        verbose_name="Самолёт",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AirlineAdministration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job", models.CharField(max_length=30, verbose_name="Должность")),
                ("clearance", models.BooleanField(default=True, verbose_name="Допуск")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ФИО сотрудника",
                    ),
                ),
            ],
        ),
    ]
