# Generated by Django 4.1.1 on 2022-11-24 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeRoom',
            fields=[
                ('id_type', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('facilities', models.TextField(verbose_name='удобства')),
                ('count_places_in_room', models.IntegerField(verbose_name='количество мест в номере')),
                ('name_type', models.CharField(max_length=400, verbose_name='название типа')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id_room', models.IntegerField(primary_key=True, serialize=False)),
                ('status_room', models.CharField(choices=[('C', 'Свободно'), ('З', 'Занято')], max_length=10)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_hotel.typeroom', verbose_name='тип комнаты')),
            ],
        ),
    ]
