# Generated by Django 4.1.1 on 2022-11-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id_room',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeroom',
            name='id_type',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
