# Generated by Django 4.1.1 on 2022-11-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_hotel', '0002_alter_room_id_room_alter_typeroom_id_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status_room',
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
