# Generated by Django 4.1.1 on 2022-11-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_hotel', '0003_remove_room_status_room_room_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('passport', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='паспорт')),
                ('phone_client', models.CharField(max_length=13, verbose_name='телефон клиента')),
                ('email_client', models.CharField(max_length=300, verbose_name='почта клиента')),
                ('name', models.CharField(max_length=20, verbose_name='имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='фамилия')),
                ('father_name', models.CharField(max_length=20, null=True, verbose_name='отчество')),
                ('address', models.CharField(max_length=300, null=True, verbose_name='адрес проживания')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('table_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='табельный номер')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО')),
                ('phone_worker', models.CharField(max_length=13, unique=True, verbose_name='телефон сотрудника')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(verbose_name='номер комнаты'),
        ),
        migrations.CreateModel(
            name='PriceConstructor',
            fields=[
                ('id_price', models.AutoField(primary_key=True, serialize=False)),
                ('data_start', models.DateField(verbose_name='Дата начала')),
                ('data_end', models.DateField(verbose_name='Дата конца')),
                ('price', models.FloatField(verbose_name='цена')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_hotel.typeroom', verbose_name='тип комнаты')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('number_contract', models.CharField(max_length=400, primary_key=True, serialize=False, verbose_name='номер договора')),
                ('data_start_living', models.DateField(verbose_name='дата заезда')),
                ('data_end_living', models.DateField(verbose_name='дата выезда')),
                ('status_book', models.CharField(choices=[('C', 'Свободно'), ('З', 'Занято')], max_length=20, verbose_name='статус бронирования')),
                ('status_payment', models.CharField(choices=[('О', 'Оплачено'), ('Н', 'Не оплачено')], max_length=20, verbose_name='статус оплаты')),
                ('identifier_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_hotel.workers', verbose_name='табельный номер сотрудника')),
                ('passport_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_hotel.client', verbose_name='пасспорт клиента')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_hotel.room', verbose_name='номер комнаты')),
            ],
        ),
    ]
