# Generated by Django 4.1.1 on 2023-01-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_hotel', '0004_client_workers_alter_room_room_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status_move_out',
            field=models.CharField(choices=[('Ж', 'живет'), ('В', 'выселен')], default='З', max_length=20, verbose_name='статус выселения'),
        ),
    ]
