# Generated by Django 4.1.1 on 2023-01-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_hotel', '0005_book_status_move_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status_move_out',
            field=models.CharField(choices=[('Ж', 'не выселен'), ('В', 'выселен')], default='З', max_length=20, verbose_name='статус выселения'),
        ),
    ]
