# Generated by Django 4.1.1 on 2023-01-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_hotel', '0007_alter_book_status_move_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status_move_out',
        ),
        migrations.AddField(
            model_name='book',
            name='status_move',
            field=models.CharField(choices=[('Ж', 'не выселен'), ('В', 'выселен')], default='не выселен', max_length=20, verbose_name='статус выселения'),
        ),
    ]
