# Generated by Django 4.1.1 on 2023-01-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_hotel', '0010_alter_book_status_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status_move',
            field=models.CharField(choices=[('не выселен', 'не выселен'), ('выселен', 'выселен')], max_length=20, verbose_name='Выселение'),
        ),
    ]
