# Generated by Django 4.1.7 on 2023-03-13 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='chekin_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='chekout_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
    ]
