# Generated by Django 4.1.7 on 2023-03-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_booking_chekin_date_booking_chekout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='chekin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='chekout_date',
            field=models.DateField(),
        ),
    ]
