# Generated by Django 4.1.7 on 2023-03-13 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_rename_chekin_date_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
