# Generated by Django 4.1.7 on 2023-03-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_room_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='prestigue',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
