# Generated by Django 4.1.7 on 2023-03-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_room_capacity_room_prestigue'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.IntegerField(null=True),
        ),
    ]
