# Generated by Django 4.1.7 on 2023-03-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_room_cost_room_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_checkin_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_checkout_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='facilities',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
