# Generated by Django 4.1.3 on 2022-11-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First_app', '0002_delete_test_carowner_home_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='Car_Model',
        ),
        migrations.RenameModel(
            old_name='DriverLicense',
            new_name='License_Model',
        ),
        migrations.RenameModel(
            old_name='CarOwner',
            new_name='Owner_Model',
        ),
        migrations.RenameModel(
            old_name='Possession',
            new_name='Possession_Model',
        ),
    ]
