# Generated by Django 4.1.3 on 2022-11-21 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0002_alter_ownership_id_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivinglicense",
            name="id_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_license",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
