# Generated by Django 4.1.3 on 2023-01-15 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('passport', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('homeTown', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('pricePerNight', models.FloatField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('number', models.IntegerField()),
                ('isBooked', models.BooleanField()),
                ('isCleaned', models.BooleanField()),
                ('roomType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Cleening',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('day', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.employee')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('checkInDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('bookStatus', models.CharField(choices=[('F', 'free'), ('B', 'booked')], max_length=20)),
                ('paymentStatus', models.CharField(choices=[('P', 'payed'), ('N', 'not payed')], max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.room')),
            ],
        ),
    ]
