# Generated by Django 4.1.3 on 2023-01-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_booking_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleening',
            name='day',
            field=models.DateField(),
        ),
    ]
