# Generated by Django 4.1.4 on 2022-12-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "passport",
                    models.TextField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Номер паспорта",
                    ),
                ),
                ("last_name", models.TextField(max_length=20, verbose_name="Фамилия")),
                ("first_name", models.TextField(max_length=20, verbose_name="Имя")),
                (
                    "patronymic",
                    models.TextField(max_length=20, null=True, verbose_name="Отчество"),
                ),
                ("city", models.TextField(max_length=30, verbose_name="Город")),
            ],
        ),
        migrations.CreateModel(
            name="TypesRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_type",
                    models.TextField(
                        choices=[
                            ("Одноместный", "Одноместный"),
                            ("Двуместный", "Двуместный"),
                            ("Трехместный", "Трехместный"),
                        ],
                        verbose_name="Тип номера",
                    ),
                ),
                (
                    "count_beds",
                    models.IntegerField(verbose_name="Кол-во спальных мест"),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
            ],
        ),
        migrations.CreateModel(
            name="Workers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.TextField(max_length=20, verbose_name="Фамилия")),
                ("first_name", models.TextField(max_length=20, verbose_name="Имя")),
                (
                    "patronymic",
                    models.TextField(max_length=20, null=True, verbose_name="Отчество"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "room_number",
                    models.TextField(
                        primary_key=True, serialize=False, verbose_name="Номер комнаты"
                    ),
                ),
                ("floor", models.PositiveIntegerField(verbose_name="Этаж")),
                (
                    "phone_number",
                    models.PositiveIntegerField(
                        max_length=11, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.typesroom",
                        verbose_name="Тип номера",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cleaning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor", models.PositiveIntegerField(verbose_name="Этаж")),
                (
                    "day_of_week",
                    models.TextField(
                        choices=[
                            ("ПН", "Понедельник"),
                            ("ВТ", "Вторник"),
                            ("СР", "Среда"),
                            ("ЧТ", "Четверг"),
                            ("ПТ", "Пятница"),
                            ("СБ", "Суббота"),
                            ("ВС", "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                (
                    "id_worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.workers"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateTimeField(verbose_name="Дата заезда")),
                ("date_end", models.DateTimeField(verbose_name="Дата выезда")),
                (
                    "total_price",
                    models.PositiveIntegerField(verbose_name="Стоимость проживания"),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.guest"
                    ),
                ),
                (
                    "room_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.room"
                    ),
                ),
            ],
        ),
    ]
