# Generated by Django 4.1.4 on 2022-12-29 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="room_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_room",
                to="hotel.room",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.PositiveIntegerField(
                null=True, verbose_name="Стоимость проживания"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="Номер комнаты"
            ),
        ),
    ]
