# Generated by Django 4.1.2 on 2022-10-23 19:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "num_race",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Номер гонки"
                    ),
                ),
                (
                    "name_race",
                    models.CharField(max_length=50, verbose_name="Название гонки"),
                ),
                (
                    "date_race",
                    models.DateTimeField(
                        unique=True, verbose_name="Дата и время гонки"
                    ),
                ),
                (
                    "place_race",
                    models.CharField(max_length=50, verbose_name="Место гонки"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRacer",
            fields=[
                ("first_name", models.CharField(max_length=30, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=30, verbose_name="Фамилия")),
                (
                    "username",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Логин",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistrationRace",
            fields=[
                (
                    "num_reg",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Номер регистрации",
                    ),
                ),
                (
                    "num_race_reg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="racers_app.race",
                    ),
                ),
                (
                    "num_user_reg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="racers_app.userracer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="race",
            name="first_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="racers_app.userracer",
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="second_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sec_place",
                to="racers_app.userracer",
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="third_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="th_pace",
                to="racers_app.userracer",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id_review", models.AutoField(primary_key=True, serialize=False)),
                ("time_race", models.DateTimeField(verbose_name="Дата и время заезда")),
                (
                    "rate",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                        verbose_name="Поставьте рейтинг",
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="Ваш Логин")),
                (
                    "type_comment",
                    models.CharField(
                        choices=[
                            ("RACE_Q", "Вопрос о гонке"),
                            ("COLLAB_Q", "Вопрос о сотрудничестве"),
                            ("OTHER", "Иное"),
                        ],
                        max_length=30,
                        verbose_name="Тип комментария",
                    ),
                ),
                ("text", models.TextField(verbose_name="Комментарий к гонке")),
                (
                    "num_race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="racers_app.race",
                    ),
                ),
            ],
        ),
    ]
