# Generated by Django 4.1.2 on 2022-10-24 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("racers_app", "0002_alter_comment_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_time",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2022, 10, 24, 15, 16, 57, 37234)
            ),
        ),
    ]
