# Generated by Django 4.1.3 on 2022-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='number',
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateField(verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(verbose_name='Check-out'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='date_time',
            field=models.DateTimeField(verbose_name='Cleaning day'),
        ),
    ]
