# Generated by Django 4.1.5 on 2023-01-21 15:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество людей",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="Подтверждение"),
                ),
            ],
            options={
                "verbose_name": "Резервирование",
                "verbose_name_plural": "Резервирования",
            },
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "destination",
                    models.CharField(max_length=200, verbose_name="Направление"),
                ),
                ("date_from", models.DateField(verbose_name="Начало")),
                ("date_to", models.DateField(verbose_name="Конец")),
                (
                    "hotel",
                    models.CharField(max_length=100, verbose_name="Название отеля"),
                ),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество мест"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тур",
                "verbose_name_plural": "Туры",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "stars",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Оценка из 10",
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="tours.reservation",
                        verbose_name="Резервация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="tour",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="tours.tour",
                verbose_name="Тур",
            ),
        ),
    ]
