# Generated by Django 3.2.8 on 2022-01-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='review',
            name='flight_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='number',
        ),
        migrations.AddField(
            model_name='review',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights_app.flight'),
        ),
    ]
