# Generated by Django 4.1.2 on 2022-12-21 11:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scenarios_app", "0003_alter_scenario_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="publish_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="scenario",
            name="publish_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenario",
                to="scenarios_app.scenario",
            ),
        ),
    ]
