# Generated by Django 4.1.2 on 2022-12-24 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scenarios_app", "0004_review_is_edited_review_publish_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="game_system",
            field=models.CharField(
                choices=[("0", "D&D"), ("1", "TEST")], default=None, max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
