# Generated by Django 4.1.2 on 2022-12-24 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios_app", "0005_alter_scenario_game_system_alter_scenario_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="game_system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scenarios_app.gamesystem",
            ),
        ),
    ]
