# Generated by Django 4.1.2 on 2023-01-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios_app", "0006_alter_scenario_game_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="image",
            field=models.TextField(
                default="https://github.com/evlko/ITMO-ICT-Frontend-2022/blob/main/labs/K33401/Kobelev/LR1/img/image-1.png"
            ),
        ),
    ]
