# Generated by Django 4.1.2 on 2023-01-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios_app", "0007_scenario_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="image",
            field=models.TextField(
                default="https://raw.githubusercontent.com/evlko/ITMO-ICT-Frontend-2022/main/labs/K33401/Kobelev/LR1/img/image-1.png"
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="short_description",
            field=models.CharField(max_length=255),
        ),
    ]
