# Generated by Django 4.1.1 on 2023-01-16 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("air_travel", "0002_remove_passenger_air_travel_passenger_air_travel"),
    ]

    operations = [
        migrations.RemoveField(model_name="passenger", name="air_travel",),
        migrations.AlterField(
            model_name="air_travel",
            name="airline",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="passenger",
            name="Air_travel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="air_travel.air_travel",
            ),
        ),
    ]
