# Generated by Django 4.1.4 on 2022-12-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtask',
            name='grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
