# Generated by Django 4.1.4 on 2022-12-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0003_createtask_sanctions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtask',
            name='subject',
            field=models.CharField(choices=[('Математика', 'Математика'), ('Физика', 'Физика'), ('Биология', 'Биология')], max_length=30),
        ),
    ]
