# Generated by Django 4.1.2 on 2023-03-14 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id_booking", models.AutoField(primary_key=True, serialize=False)),
                ("date_start", models.DateField(verbose_name="Дата поселения")),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата выселения"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cleaner",
            fields=[
                ("id_cleaner", models.AutoField(primary_key=True, serialize=False)),
                (
                    "last_name_cleaner",
                    models.CharField(max_length=120, verbose_name="Фамилия служащего"),
                ),
                (
                    "first_name_cleaner",
                    models.CharField(max_length=120, verbose_name="Имя служащего"),
                ),
                (
                    "patronymic_cleaner",
                    models.CharField(max_length=120, verbose_name="Отчество служащего"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                ("id_floor", models.AutoField(primary_key=True, serialize=False)),
                ("floor_num", models.IntegerField(verbose_name="Этаж")),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                ("id_price", models.AutoField(primary_key=True, serialize=False)),
                (
                    "room_type",
                    models.CharField(
                        choices=[("s", "single"), ("d", "double"), ("t", "triple")],
                        max_length=1,
                        verbose_name="Тип номера",
                    ),
                ),
                ("price_daily", models.FloatField(verbose_name="Стоимость за сутки")),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id_schedule", models.AutoField(primary_key=True, serialize=False)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("mon", "monday"),
                            ("tue", "tuesday"),
                            ("wed", "wednesday"),
                            ("thu", "thursday"),
                            ("fri", "friday"),
                            ("sat", "saturday"),
                            ("sun", "sunday"),
                        ],
                        max_length=3,
                        verbose_name="День недели",
                    ),
                ),
                (
                    "id_cleaner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_app.cleaner",
                        verbose_name="Служащий",
                    ),
                ),
                (
                    "id_floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_app.floor",
                        verbose_name="Этаж для уборки",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id_room", models.AutoField(primary_key=True, serialize=False)),
                (
                    "phone",
                    models.CharField(max_length=7, verbose_name="Номер телефона"),
                ),
                (
                    "id_floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_app.floor",
                        verbose_name="Этаж",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_app.price",
                        verbose_name="Тип номера",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "passport",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Номер паспорта",
                    ),
                ),
                (
                    "last_name_client",
                    models.CharField(
                        max_length=120, verbose_name="Фамилия проживающего"
                    ),
                ),
                (
                    "first_name_client",
                    models.CharField(max_length=120, verbose_name="Имя проживающего"),
                ),
                (
                    "patronymic_client",
                    models.CharField(
                        max_length=120, verbose_name="Отчество проживающего"
                    ),
                ),
                ("city", models.CharField(max_length=120, verbose_name="Родной город")),
                (
                    "rooms",
                    models.ManyToManyField(
                        related_name="room_client",
                        through="hotel_app.Booking",
                        to="hotel_app.room",
                        verbose_name="Номера",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cleaner",
            name="floors",
            field=models.ManyToManyField(
                related_name="floor_cleaner",
                through="hotel_app.Schedule",
                to="hotel_app.floor",
                verbose_name="Обслуживаемые этажи",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="id_client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hotel_app.client",
                verbose_name="Проживающий",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="id_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hotel_app.room",
                verbose_name="Выделенный номер",
            ),
        ),
    ]
