# Generated by Django 4.1.2 on 2023-03-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0003_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
