# Generated by Django 4.1.5 on 2023-02-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_total_amount_book_total_stock_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='readingroombookuser',
            name='date_check',
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=17, verbose_name='ISBN'),
        ),
        migrations.AddConstraint(
            model_name='readingroombookuser',
            constraint=models.CheckConstraint(check=models.Q(('returned_date__gte', models.F('borrow_date'))), name='date_check', violation_error_message='Borrow date must be earlier than returned date.'),
        ),
    ]
