# Generated by Django 4.1.5 on 2023-02-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bookuser_returned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='name',
            field=models.CharField(default='roomy', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingroom',
            name='name',
            field=models.CharField(default='roomyrom', max_length=100),
            preserve_default=False,
        ),
    ]
