# Generated by Django 4.1.5 on 2023-02-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_readingroombookuser_date_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingroombook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book', unique=True),
        ),
    ]
