site_name: Chub Ilia, K33401

theme:
    name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
nav:
 - Laboratory work №3:
    - Task: laboratory-work-3-task.md
    - Models: laboratory-work-3-models.md
    - Views: laboratory-work-3-views.md
    - Serializers: laboratory-work-3-serializers.md
    - URLs: laboratory-work-3-url.md
    - API: laboratory-work-3-api.md
