# Generated by Django 4.1.7 on 2023-02-28 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Airline name')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Airline link')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='City name')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='City link')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=10, verbose_name='Flight number')),
                ('departure', models.DateTimeField(verbose_name='Departure datetime')),
                ('arrival', models.DateTimeField(verbose_name='Arrival datetime')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airline')),
                ('city_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_from', to='flights.city')),
                ('city_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_to', to='flights.city')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=10)),
                ('passenger_name', models.CharField(max_length=32)),
                ('passenger_surname', models.CharField(max_length=32)),
                ('passenger_passport', models.CharField(max_length=10)),
                ('seat', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('review_text', models.TextField(blank=True, default=None, null=True)),
                ('rate', models.IntegerField(blank=True, default=None, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
