# Generated by Django 4.0.1 on 2023-01-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_hotel.guest'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_hotel.room'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_hotel.staff'),
        ),
    ]
