# Generated by Django 4.0.1 on 2023-01-26 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_hotel', '0002_alter_checkin_guest_alter_checkin_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='cleaners',
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_hotel.room'),
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_hotel.staff'),
        ),
    ]
