# Generated by Django 4.1.4 on 2022-12-17 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BooksOnHands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_register",
                    models.DateField(blank=True, null=True, verbose_name="Дата выдачи"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя зала")),
                ("capacity", models.IntegerField(verbose_name="Вместимость")),
            ],
        ),
        migrations.CreateModel(
            name="InstanceBook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID экземпляра книги",
                    ),
                ),
                ("cypher", models.CharField(max_length=20, verbose_name="Шифр")),
                ("year_published", models.IntegerField(verbose_name="Год издания")),
                ("section", models.CharField(max_length=20, verbose_name="Раздел")),
                ("publisher", models.CharField(max_length=20, verbose_name="Издатель")),
                (
                    "condition",
                    models.CharField(
                        choices=[("g", "good"), ("n", "normal"), ("b", "bad")],
                        max_length=1,
                        verbose_name="Состояние экземпляра",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_app.book",
                        verbose_name="Книга",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "library_pass",
                    models.CharField(max_length=20, verbose_name="Читательский билет"),
                ),
                ("name", models.CharField(max_length=70, verbose_name="ФИО")),
                (
                    "passport",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Паспорт"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="День рождения"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефона"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("e", "elementary"),
                            ("s", "secondary"),
                            ("c", "college"),
                        ],
                        default="e",
                        max_length=1,
                        verbose_name="Образование",
                    ),
                ),
                (
                    "degree",
                    models.BooleanField(
                        default=False, verbose_name="Есть ли уч степент"
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(verbose_name="Дата регистрации"),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_app.hall",
                        verbose_name="Зал читателя",
                    ),
                ),
                (
                    "instances_on_hands",
                    models.ManyToManyField(
                        related_name="instance_reader",
                        through="library_app.BooksOnHands",
                        to="library_app.instancebook",
                        verbose_name="Книги на руках",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReaderHall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата закрепления зала"
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_app.hall",
                        verbose_name="Зал",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_app.reader",
                        verbose_name="Читатель",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstancePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_app.instancebook",
                        verbose_name="Экземпляр книги",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_app.hall",
                        verbose_name="Зал библиотеки",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hall",
            name="books",
            field=models.ManyToManyField(
                related_name="instance_place",
                through="library_app.InstancePlace",
                to="library_app.instancebook",
                verbose_name="Книги",
            ),
        ),
        migrations.AddField(
            model_name="hall",
            name="readers",
            field=models.ManyToManyField(
                related_name="reader_place",
                through="library_app.ReaderHall",
                to="library_app.reader",
                verbose_name="Читатели",
            ),
        ),
        migrations.AddField(
            model_name="booksonhands",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="library_app.instancebook",
                verbose_name="Экземпляр книги",
            ),
        ),
        migrations.AddField(
            model_name="booksonhands",
            name="reader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="library_app.reader",
                verbose_name="Читатель",
            ),
        ),
    ]
