# Generated by Django 4.1.4 on 2022-12-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "library_app",
            "0002_booksonhands_hall_instancebook_reader_readerhall_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instancebook",
            name="section",
        ),
        migrations.AddField(
            model_name="book",
            name="section",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Раздел"
            ),
        ),
    ]
