# Generated by Django 4.1.4 on 2022-12-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0003_remove_instancebook_section_book_section"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reader",
            old_name="education",
            new_name="education_level",
        ),
        migrations.RemoveField(
            model_name="reader",
            name="hall",
        ),
        migrations.AlterField(
            model_name="reader",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Телефон"
            ),
        ),
    ]
