# Generated by Django 4.1.2 on 2022-10-27 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='date',
        ),
        migrations.AddField(
            model_name='conference',
            name='end_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 21, 49, 9, 798592)),
        ),
        migrations.AddField(
            model_name='conference',
            name='location',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='conference',
            name='rules',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='conference',
            name='start_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 21, 49, 9, 798592)),
        ),
        migrations.AddField(
            model_name='conference',
            name='topics',
            field=models.TextField(default=None),
        ),
    ]
