# Generated by Django 4.1.4 on 2022-12-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("megaultrabooking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="state",
            field=models.CharField(
                choices=[("PD", "Ожидает"), ("CL", "Отменено"), ("FN", "Прошедшее")],
                default="PD",
                max_length=2,
            ),
        ),
    ]
