site_name: Baldina Daria, K33401

theme:
    name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
nav:
 - Знакомство: index.md
 - Лабораторная работа №1: lr1.md
 - Лабраторная работа №2: lr2.md
 - Практическая работа №3.1: prac31.md