site_name: Rybkin M A, K33402

theme:
    name: material
@@ -11,5 +11,7 @@ markdown_extensions:
  - pymdownx.superfences

nav:
 - Знакомство: index.md
 - Лабораторная работа №1: lab1.md
 - Лабораторная работа №2: lab2.md
