# Generated by Django 4.1.2 on 2022-11-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_rename_owner_license_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
