# Generated by Django 4.1.5 on 2023-01-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_event_category_remove_event_district_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("sport", "Спорт и фитнес"),
                    ("art", "Искусство и культура"),
                    ("nature", "Природа"),
                    ("career", "Карьера и образование"),
                    ("theatre", "Театры"),
                    ("concert", "Концерты"),
                ],
                default="sport",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="district",
            field=models.CharField(
                choices=[
                    ("any", "Любой"),
                    ("admiral", "Адмиралтейский"),
                    ("vasileostrov", "Василеостровской"),
                    ("vyborg", "Выборгский"),
                    ("kalininsk", "Калининский"),
                    ("kirov", "Кировский"),
                    ("krasnogvard", "Красногвардейский"),
                    ("krasnosel", "Красносельский"),
                    ("kronshtad", "Кронштадский"),
                    ("moskovsk", "Московский"),
                    ("nevsk", "Невский"),
                    ("petrograd", "Петроградский"),
                    ("center", "Центральный"),
                ],
                default="sport",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="type_event",
            field=models.CharField(
                choices=[("offline", "Очно"), ("online", "Онлайн")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
