# Generated by Django 4.1.5 on 2023-01-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_event_map_alter_event_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
    ]
