# Generated by Django 4.1.5 on 2023-01-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_remove_event_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(default="2022-11-02 19:00"),
            preserve_default=False,
        ),
    ]
