# Generated by Django 4.1.5 on 2023-01-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_usersevents"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.TextField(
                default="https://e7.pngegg.com/pngimages/398/54/png-clipart-silhouette-graphics-male-silhouette-animals-hand.png"
            ),
        ),
    ]
