# Generated by Django 4.1.5 on 2023-01-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
    ]
